#!/bin/sh

if [ "$1" = "start" ]; then
    mkdir -p /mnt/sdcard

    if [ -b /dev/mmcblk0p1 ]; then
        mount /dev/mmcblk0p1 /mnt/sdcard
    elif [ -b /dev/mmcblk0 ]; then
        mount /dev/mmcblk0 /mnt/sdcard
    fi

    echo 3 4 1 7 > /proc/sys/kernel/printk

    sleep 1
    /etc/setStaticNet.sh
    /etc/test_ping.sh &
fi
