#!/bin/sh

USER_INTERFACES="/mnt/overlay/upper/etc/network/interfaces"

log() {
	echo "PREINIT: $*"
}

# user_defined_old_interface_config
#
# Checks if the user has configured an interfaces file for fw < v2.1.
# Requires the overlay filesystem to be mounted.
#
user_defined_old_interface_config() {
    if [ ! -f "$USER_INTERFACES" ]; then
        # No user override
        return 1
    fi

    local is_new
    local has_eth0

    grep -qE "node[1-4]|ge[01]" "$USER_INTERFACES" && is_new=1 || is_new=0
    grep -qE "^[^#]*eth0" "$USER_INTERFACES" && has_eth0=1 || has_eth0=0

    if [ "$is_new" -eq 0 ] || [ "$has_eth0" -eq 1 ]; then
        return 0
    else
        return 1
    fi
}

migrate_interfaces_v2_1() {
if user_defined_old_interface_config; then
    mv "$USER_INTERFACES" "${USER_INTERFACES}_bak"
    # Add a comment block at the top of the new file
    sed -i '1i# This file was automatically updated by a migration script\n#\
        The original /etc/network/interfaces file is renamed to `interfaces_bak`.\n#\
        From v2.1 onwards, eth0 is deprecated and configuration needs to be applied to interface br0 instead.\n#' "/etc/network/interfaces"
    log migrated interfaces file
fi
}

#
# is_safemode
#
# Returns true IFF we were told to boot in safemode
# (such as if the user held KEY1 for a few seconds at power on)
#
is_safemode() {
	grep -q 'safemode' /proc/cmdline
}

#
# pivot_overlay OVERLAYDIR
#
# Establish an overlayfs over the read-only rootfs (storing data in OVERLAYDIR)
# and make it the root
#
pivot_overlay() {
	MOUNTS="dev proc tmp sys"
	NEWROOT=/tmp/newroot
	OLDROOT=/mnt/rom
	UPPER=$1/upper
	WORK=$1/work

	[ -d $UPPER ] || mkdir -p $UPPER
	[ -d $WORK ] || mkdir -p $WORK

	mkdir $NEWROOT
	mount -t overlay overlay -o lowerdir=/,upperdir=$UPPER,workdir=$WORK $NEWROOT

	[ -d $NEWROOT/$OLDROOT ] || mkdir -p $NEWROOT/$OLDROOT

	log Pivoting root
	pivot_root $NEWROOT $NEWROOT/$OLDROOT
	for mountpoint in $MOUNTS $1; do
		if mountpoint -q $OLDROOT/$mountpoint; then
			mount --move $OLDROOT/$mountpoint /$mountpoint;
		fi
	done

	# Clean up, now that nothing is mounted here
	rmdir $NEWROOT
}

#
# preinit
#
# Main function
#
preinit() {
	OVERLAY=/mnt/overlay

	log Starting

	# Need /dev, /proc, and /tmp mounted, and /sys for good measure
	# /dev is automounted by kernel
	mount -t proc /proc /proc
	mount -t tmpfs /tmp /tmp
	mount -t sysfs /sys /sys

	if is_safemode || ! mount_overlay; then
		log Entering safemode
		OVERLAY=/tmp/safemode
		export IS_SAFEMODE=1
	fi

	pivot_overlay $OVERLAY

    migrate_interfaces_v2_1

	log Beginning init
	exec /sbin/init
}


preinit
